### ISSUE TITLE
Updating AAAA record: "connection timed out; no servers could be reached"

### ISSUE THREAD

**Issue by DesertCookie** [oznu/docker-cloudflare-ddns#45]
I get the following error from my container designated to update my IPv6 with cloudflare: `ERROR: Failed to update CloudFlare DNS record rhprivate.de from 2000:16b8:55e4:1300:4972:6e17:cb16:5dd3 to ;; connection timed out; no servers could be reached`.

The container is created in docker-compose using the following config:
```YML
cloudflare_ddns_v6:
  container_name: cloudflare_ddns_v6
  image: oznu/cloudflare-ddns:latest
  restart: always
  network_mode: host
  environment:
    - ZONE=example.com
    - API_KEY=abcdefghijklmnopqrstuvwxyz
    - PROXIED=TRUE
    - RRTYPE=AAAA
```

I have a container using a nearly identical configuration for IPv4 updates that works mostly flawlessly; it's only problem: despite of the flag `PROXIED=TRUE` it always changes the A record to be unproxied.
