### ISSUE TITLE
Cloudflare update deactivates HTTP proxy

### ISSUE THREAD

**Issue by jwillmer** [oznu/docker-cloudflare-ddns#7]
I need the HTTP proxy in cloudflare but the image disables it at each update.

![error](https://user-images.githubusercontent.com/1503577/40710398-d28da48c-63f8-11e8-9451-8a205fa934b6.png)

**Comment by oznu** [comment]
> `-e PROXIED` - Set to `true` to make traffic go through the CloudFlare CDN. Defaults to `false`

In your docker-compose add this to your environment section:

`- PROXIED=true`

**Comment by jwillmer** [comment]
I start to feel stupid for not reading the man. Works as intended!

For the interested 3d-party, my docker-compose file now supports IPv6 and proxy mode:
```
  cloudflare-ddns:
    image: oznu/cloudflare-ddns
    container_name: cloudflare-ddns
    network_mode: host
    restart: always
    environment:
      - EMAIL=hello@example.com
      - API_KEY=xxxxxxx
      - ZONE=example.com
      - SUBDOMAIN=subdomain
      - RRTYPE=AAAA
      - PROXIED=true
```
