### ISSUE TITLE
unable to spawn /var/run/s6/etc/cont-init.d/30-cloudflare-setup: Permission denied

### ISSUE THREAD

**Issue by JonasVgt** [oznu/docker-cloudflare-ddns#70]
Hello,
for quite some time this Container ran perfectly for me. But for a few days it doesn't work anymore.

### The Problem:
The Container doesn't start and is throwing repeatably the following error
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 30-cloudflare-setup: executing... 
foreground: warning: unable to spawn /var/run/s6/etc/cont-init.d/30-cloudflare-setup: Permission denied
foreground: fatal: unable to wait for /var/run/s6/etc/cont-init.d/30-cloudflare-setup: No child process
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 50-remove-record: executing... 
s6-maximumtime: fatal: unable to spawn /var/run/s6/etc/cont-finish.d/50-remove-record: Permission denied
[cont-finish.d] 50-remove-record: exited 111.
[cont-finish.d] done.
```

### My Setup:
I am running `Raspbian GNU/Linux 10 (buster)` on my Raspberry Pi 4B. 

Docker-compose:
```
version: '2'
services:
  nextcloud_ipv6:
    image: oznu/cloudflare-ddns:latest
    restart: always
    network_mode: host
    environment:
      - API_KEY=##################################
      - ZONE=example.com
      - SUBDOMAIN=cloud
      - PROXIED=true
      - PUID = 998
      - PGID = 100
      - RRTYPE=AAAA
      - DNS_SERVER=1.1.1.1
      - INTERFACE=eth0
      - CRON=*/30 * * * *
```

Thank you for your Help
