### ISSUE TITLE
Can update zone or subdomains, but not both

### ISSUE THREAD

**Issue by acollien** [oznu/docker-cloudflare-ddns#81]
Ran into the issue when I was trying to get the app to update the 'www' A record on cloudflare. Popped it in the subdomain field of the app, and then checked back after running it. My main website A record had not updated, but the www had. It also works with adding multiple subdomains - appears to update them all fine, but again not the main wbsite A record. When I remove all the subdomains and run it, the main website A record updates. Appear one do subdomains, or the main record - not both. Any ideas?

**Comment by thijsjek** [comment]
I just created 2 separated docker containers. 
One without subdomain=
and one with subdomain=www,cloud,etc

**Comment by QuanDev2** [comment]
@thijsjek can you use commas to separate multiple subdomains?

**Comment by PackElend** [comment]
still, the case that only one of the A-Types gets updated?
first A got updated but not the second one.
![image](https://user-images.githubusercontent.com/3542031/178160141-d453f089-5b2f-4fb5-ae53-71d2246889cf.png)

**Comment by thijsjek** [comment]
So, the container let's you put in multiple like comma seperated domains or multiple -e subdomains, but that does not work. I didnt notice because my IP didn't change until I setup like below
I eventually just use 2 containers. One for mydomain.com and one for *.mydomain.com. 

To adjust multiple subdomains, I think you have to create several containers.

**Comment by PackElend** [comment]
so you do
CONTAINER: TLD
```
version: '2'
services:
  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      - API_KEY=xxxxxxx
      - ZONE=mydomain.com

```

CONTAINER: suddomains
```
version: '2'
services:
  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      - API_KEY=xxxxxxx
      - ZONE=*.mydomain.com
      - PROXIED=false

```
