### ISSUE TITLE
Updating AAAA record: "connection timed out; no servers could be reached"

### ISSUE THREAD

**Issue by DerPW** [oznu/docker-cloudflare-ddns#83]
It was working for a while and then i checked a few days later and saw this error in the log when trying to change AAAA record:

```
Updating CloudFlare DNS record mydomain.com from 1:1:1:1:1:1:1:1 to ;; connection timed out; no servers could be reached...

ERROR: Failed to update CloudFlare DNS record mydomain.com from 1:1:1:1:1:1:1:1 to ;; connection timed out; no servers could be reached
```

I am using portainer und this is my config:
```
version: '2'
services:
  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      - API_KEY=abcdefghijkmnop
      - ZONE=mydomain.com
      - PROXIED=false
      - RRTYPE=AAAA

```
